minutes_back = 60
slack_url = "https://hooks.slack.com/services/********************"
age_off = 30
base_url = "http://localhost/"
logs_bucket = "bucket_name"
secret_key = "NWBUdSXUzHxNoO8g" # Change me.

[accounts]
111111111111 = ["us-east-1"]

[email]
sender = "adam@example.com"
receivers = ["adam@example.com"]
smtp_server = "smtp.example.com"
password = "hunter2"

[users]
admin = "password123"
